import {
  createMockFinancialAnalysisProvider,
  createVertexFinancialAnalysisProvider,
  type FinancialAnalysisAiProvider,
} from '@hidmo/ai'
import { generateFinancialAnalysis } from '@hidmo/analysis'
import { getWorkerEnvironment } from '@hidmo/config'
import {
  createDatabase,
  createDatabasePool,
  createRepositories,
} from '@hidmo/database'
import { createLogger } from '@hidmo/logging'
import { createPlaidProvider, parseLocalWrappingKey } from '@hidmo/plaid'
import {
  plaidErrorCode,
  refreshClassifications,
  synchronizePlaidConnection,
} from '@hidmo/sync'

import { runPlaidSyncJob } from './plaid-sync-handler.js'
import { createWorkerServer, parseAllowedTaskQueues } from './server.js'

const environment = getWorkerEnvironment()
const logger = createLogger('worker', environment.LOG_LEVEL)
const pool = createDatabasePool(environment.DATABASE_URL)
const repositories = createRepositories(createDatabase(pool))
const provider = createPlaidProvider({
  clientId: environment.PLAID_CLIENT_ID,
  secret: environment.PLAID_SECRET,
  environment: environment.PLAID_ENV,
})
const wrappingKey = parseLocalWrappingKey(
  environment.LOCAL_TOKEN_ENCRYPTION_KEY,
)

function createFinancialAnalysisProvider(): FinancialAnalysisAiProvider {
  if (environment.AI_PROVIDER === 'mock') {
    return createMockFinancialAnalysisProvider()
  }

  if (
    environment.VERTEX_AI_PROJECT_ID === undefined ||
    environment.VERTEX_AI_LOCATION === undefined ||
    environment.VERTEX_AI_MODEL === undefined
  ) {
    throw new Error(
      'Vertex AI provider requires VERTEX_AI_PROJECT_ID, VERTEX_AI_LOCATION, and VERTEX_AI_MODEL',
    )
  }

  return createVertexFinancialAnalysisProvider({
    projectId: environment.VERTEX_AI_PROJECT_ID,
    location: environment.VERTEX_AI_LOCATION,
    model: environment.VERTEX_AI_MODEL,
  })
}

const financialAnalysisProvider = createFinancialAnalysisProvider()
const server = createWorkerServer({
  allowedTaskQueues: parseAllowedTaskQueues(
    environment.CLOUD_TASKS_ALLOWED_QUEUES,
  ),
  financialAnalysis: async ({ userId, period }) => {
    const result = await generateFinancialAnalysis({
      userId,
      period,
      repositories,
      aiProvider: financialAnalysisProvider,
    })
    logger.info(
      {
        userId,
        period,
        status: result.status,
        snapshotId: result.snapshotId,
        jobId: result.jobId,
        inputHash: result.inputHash,
        formulaVersion: result.formulaVersion,
        aiProvider: result.aiMetadata?.provider,
        aiModel: result.aiMetadata?.model,
      },
      'Financial analysis generated by worker',
    )
    return result
  },
  logger,
  plaidSync: async ({ userId, connectionId, syncJobId }) => {
    const syncJob = await repositories.syncJobs.getLogContext(syncJobId)
    const logContext = {
      userId,
      connectionId,
      syncJobId,
      operation: syncJob?.operation ?? 'unknown',
      trigger: syncJob?.trigger ?? 'unknown',
      previousStatus: syncJob?.status ?? 'unknown',
    }

    try {
      const result = await runPlaidSyncJob(
        { userId, connectionId, syncJobId },
        {
          markRunning: repositories.syncJobs.markRunning.bind(
            repositories.syncJobs,
          ),
          markSucceeded: repositories.syncJobs.markSucceeded.bind(
            repositories.syncJobs,
          ),
          markFailed: repositories.syncJobs.markFailed.bind(
            repositories.syncJobs,
          ),
          synchronize: ({ userId, connectionId }) =>
            synchronizePlaidConnection({
              userId,
              connectionId,
              provider,
              repositories,
              wrappingKey,
            }),
          refreshClassifications: (userId) =>
            refreshClassifications(userId, repositories),
        },
      )
      logger.info(
        { ...logContext, ...result },
        'Plaid transactions synchronized by worker',
      )
      return result
    } catch (error) {
      logger.error(
        {
          ...logContext,
          errorCode: plaidErrorCode(error),
          errorName: error instanceof Error ? error.name : 'UnknownError',
        },
        'Plaid transaction synchronization failed by worker',
      )
      throw error
    }
  },
  pool,
  taskExecutions: repositories.taskExecutions,
})

server.listen(environment.WORKER_PORT, '0.0.0.0', () => {
  logger.info({ port: environment.WORKER_PORT }, 'worker listening')
})

async function shutdown(signal: string) {
  logger.info({ signal }, 'worker shutdown started')
  server.close()
  await pool.end()
}

process.once('SIGINT', () => {
  void shutdown('SIGINT')
})

process.once('SIGTERM', () => {
  void shutdown('SIGTERM')
})
