import type {
  Account,
  BudgetLine,
  Debt,
  Transaction,
  TransactionSplit,
} from './domain.js'

export const syntheticHousehold = {
  accounts: [
    {
      id: 'checking-1',
      name: 'Household checking',
      kind: 'checking',
      balanceMinor: 450_000n,
      currency: 'USD',
      balanceAsOf: '2026-06-30',
      balanceSource: 'connected',
      dataQuality: 'verified',
    },
    {
      id: 'savings-1',
      name: 'Emergency savings',
      kind: 'savings',
      balanceMinor: 800_000n,
      currency: 'USD',
      balanceAsOf: '2026-06-30',
      balanceSource: 'connected',
      dataQuality: 'verified',
    },
    {
      id: 'brokerage-1',
      name: 'Brokerage',
      kind: 'brokerage',
      balanceMinor: 1_500_000n,
      currency: 'USD',
      balanceAsOf: '2026-06-30',
      balanceSource: 'connected',
      dataQuality: 'verified',
    },
    {
      id: 'retirement-1',
      name: '401(k)',
      kind: 'retirement',
      balanceMinor: 3_200_000n,
      currency: 'USD',
      balanceAsOf: '2026-06-30',
      balanceSource: 'connected',
      dataQuality: 'verified',
    },
    {
      id: 'credit-card-1',
      name: 'Rewards card',
      kind: 'credit_card',
      balanceMinor: 210_000n,
      creditLimitMinor: 1_000_000n,
      currency: 'USD',
      balanceAsOf: '2026-06-30',
      balanceSource: 'connected',
      dataQuality: 'verified',
    },
    {
      id: 'auto-loan-1',
      name: 'Auto loan',
      kind: 'auto_loan',
      balanceMinor: 1_250_000n,
      currency: 'USD',
      balanceAsOf: '2026-06-30',
      balanceSource: 'connected',
      dataQuality: 'estimated',
    },
    {
      id: 'personal-loan-1',
      name: 'Personal loan',
      kind: 'personal_loan',
      balanceMinor: 480_000n,
      currency: 'USD',
      balanceAsOf: '2026-06-30',
      balanceSource: 'manual',
      dataQuality: 'verified',
    },
  ] satisfies Account[],
  transactions: [
    {
      id: 'payroll',
      accountId: 'checking-1',
      postedDate: '2026-06-01',
      amountMinor: 500_000n,
      currency: 'USD',
      direction: 'inflow',
      economicType: 'income',
      category: 'income:payroll',
      state: 'posted',
      reviewed: true,
    },
    {
      id: 'rent',
      accountId: 'checking-1',
      postedDate: '2026-06-02',
      amountMinor: -180_000n,
      currency: 'USD',
      direction: 'outflow',
      economicType: 'expense',
      category: 'housing:rent',
      state: 'posted',
      reviewed: true,
    },
    {
      id: 'groceries',
      accountId: 'credit-card-1',
      postedDate: '2026-06-05',
      amountMinor: -62_000n,
      currency: 'USD',
      direction: 'outflow',
      economicType: 'expense',
      category: 'food:groceries',
      state: 'posted',
      reviewed: true,
    },
    {
      id: 'grocery-refund',
      accountId: 'credit-card-1',
      postedDate: '2026-06-08',
      amountMinor: 7_000n,
      currency: 'USD',
      direction: 'inflow',
      economicType: 'refund',
      category: 'food:groceries',
      state: 'posted',
      reviewed: true,
    },
    {
      id: 'checking-to-savings',
      accountId: 'checking-1',
      postedDate: '2026-06-10',
      amountMinor: -50_000n,
      currency: 'USD',
      direction: 'outflow',
      economicType: 'transfer',
      category: 'transfer',
      state: 'posted',
      reviewed: true,
    },
    {
      id: 'savings-from-checking',
      accountId: 'savings-1',
      postedDate: '2026-06-10',
      amountMinor: 50_000n,
      currency: 'USD',
      direction: 'inflow',
      economicType: 'transfer',
      category: 'transfer',
      state: 'posted',
      reviewed: true,
    },
    {
      id: 'card-payment-checking',
      accountId: 'checking-1',
      postedDate: '2026-06-15',
      amountMinor: -100_000n,
      currency: 'USD',
      direction: 'outflow',
      economicType: 'debt_payment',
      category: 'debt:credit-card',
      state: 'posted',
      reviewed: true,
    },
    {
      id: 'card-payment-card',
      accountId: 'credit-card-1',
      postedDate: '2026-06-15',
      amountMinor: 100_000n,
      currency: 'USD',
      direction: 'inflow',
      economicType: 'debt_payment',
      category: 'debt:credit-card',
      state: 'posted',
      reviewed: true,
    },
    {
      id: 'card-interest',
      accountId: 'credit-card-1',
      postedDate: '2026-06-20',
      amountMinor: -3_500n,
      currency: 'USD',
      direction: 'outflow',
      economicType: 'expense',
      category: 'debt:interest',
      state: 'posted',
      reviewed: true,
    },
    {
      id: 'pending-dining',
      accountId: 'credit-card-1',
      postedDate: '2026-06-30',
      amountMinor: -4_500n,
      currency: 'USD',
      direction: 'outflow',
      economicType: 'expense',
      category: 'food:dining',
      state: 'pending',
      reviewed: false,
    },
  ] satisfies Transaction[],
  loanPaymentTransaction: {
    id: 'loan-payment',
    accountId: 'checking-1',
    postedDate: '2026-06-25',
    amountMinor: -50_000n,
    currency: 'USD',
    direction: 'outflow',
    economicType: 'debt_payment',
    category: 'debt:personal-loan',
    state: 'posted',
    reviewed: true,
  } satisfies Transaction,
  loanPaymentSplits: [
    {
      id: 'loan-principal',
      transactionId: 'loan-payment',
      amountMinor: -42_000n,
      economicType: 'debt_payment',
      category: 'debt:principal',
    },
    {
      id: 'loan-interest',
      transactionId: 'loan-payment',
      amountMinor: -7_000n,
      economicType: 'expense',
      category: 'debt:interest',
    },
    {
      id: 'loan-fee',
      transactionId: 'loan-payment',
      amountMinor: -1_000n,
      economicType: 'expense',
      category: 'debt:fees',
    },
  ] satisfies TransactionSplit[],
  budget: [
    { category: 'housing:rent', plannedMinor: 180_000n },
    { category: 'food:groceries', plannedMinor: 60_000n },
    { category: 'debt:interest', plannedMinor: 5_000n },
  ] satisfies BudgetLine[],
  debts: [
    {
      id: 'credit-card-1',
      name: 'Rewards card',
      kind: 'credit_card',
      balanceMinor: 210_000n,
      aprBps: 2_499,
      minimumPaymentMinor: 8_000n,
      currency: 'USD',
    },
    {
      id: 'personal-loan-1',
      name: 'Personal loan',
      kind: 'personal_loan',
      balanceMinor: 480_000n,
      aprBps: 1_150,
      minimumPaymentMinor: 15_000n,
      currency: 'USD',
    },
    {
      id: 'auto-loan-1',
      name: 'Auto loan',
      kind: 'auto_loan',
      balanceMinor: 1_250_000n,
      aprBps: 650,
      minimumPaymentMinor: 32_000n,
      currency: 'USD',
    },
  ] satisfies Debt[],
} as const
